# Generated by Django 5.0.6 on 2024-05-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='user_images/default.jpg', upload_to='user_images'),
        ),
    ]
