# Generated by Django 5.0.6 on 2024-05-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_event_organizers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reg_deadline',
            field=models.DateField(null=True),
        ),
    ]
