# Generated by Django 5.0.6 on 2024-05-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_event_reg_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reg_deadline',
            field=models.DateField(),
        ),
    ]
