# Generated by Django 5.0.6 on 2024-05-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['event__date']},
        ),
    ]
