# Generated by Django 5.0.6 on 2024-05-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_booking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='avatar',
            field=models.ImageField(default='default.webp', upload_to='event_images'),
        ),
    ]
