# Generated by Django 5.0.6 on 2024-05-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_event_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='avatar',
            field=models.ImageField(default='event_images/default.webp', upload_to='event_images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event_images/event.jpg', upload_to='event_images'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='image',
            field=models.ImageField(default='organizer_images/organizer.jpg', upload_to='organizer_images'),
        ),
    ]
